version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: jarvis_db
      POSTGRES_USER: jarvis_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      bash -c "python manage.py migrate &&
               python create_superuser.py &&
               python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=True
      - DJANGO_SUPERUSER_USERNAME=Tony
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=1111
      - POSTGRES_DB=jarvis_db
      - POSTGRES_USER=jarvis_user
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
