# Generated by Django 5.0.7 on 2024-08-10 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_tag_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tag',
            name='owners',
            field=models.ManyToManyField(blank=True, null=True, related_name='notes_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='owner',
        ),
    ]
