# Generated by Django 5.0.7 on 2024-08-10 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_tag_unique_together_tag_owners_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='owners',
            field=models.ManyToManyField(related_name='notes_tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
