# Generated by Django 5.0.7 on 2024-08-10 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_remove_tag_owners_tag_owners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='owners',
            new_name='owner',
        ),
    ]
