# Generated by Django 5.0.7 on 2024-07-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_file_name_file_uploaded_at_alter_file_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('other', 'Other')], max_length=50),
        ),
    ]
