# Generated by Django 5.0.7 on 2024-07-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activationtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivationToken',
        ),
    ]
