# Generated by Django 5.0.7 on 2024-07-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_file_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='storage_limit',
            field=models.BigIntegerField(default=52428800),
        ),
    ]
