# Generated by Django 5.0.7 on 2024-07-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_email_confirmed_activationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_confirmed',
        ),
        migrations.DeleteModel(
            name='ActivationToken',
        ),
    ]
