# Generated by Django 5.0.7 on 2024-07-28 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_avatar'),
        ('notes', '0002_rename_user_note_owner'),
        ('task_manager', '0003_tag_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='notes.note'),
        ),
        migrations.AddField(
            model_name='file',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='task_manager.task'),
        ),
    ]
