# Generated by Django 5.0.7 on 2024-07-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
