# Generated by Django 5.0.7 on 2024-07-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag_note_created_at_note_title_note_updated_at_and_more'),
        ('core', '0006_delete_contact'),
    ]

    operations = [
    ]
